#!/usr/bin/env bash
# bootstrap.sh — Runtime onboarding script
# Reads onboard.yml at startup via python3 + PyYAML.
# Generated by project-onboard skill.
#
# Usage:
#   ./bootstrap.sh                    # prod mode (default), interactive
#   ./bootstrap.sh --mode dev         # maintainer/contributor setup
#   ./bootstrap.sh --mode prod        # end-user setup and deploy
#   ./bootstrap.sh --non-interactive  # use all defaults, no prompts
#   ./bootstrap.sh --check-only       # run validation checks only
#   ./bootstrap.sh --dry-run          # show what would happen without executing
#   ./bootstrap.sh --help             # show usage

set -euo pipefail

# ─── Colors ──────────────────────────────────────────────────────────────────

if [[ -t 1 ]]; then
    RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
    BLUE='\033[0;34m'; BOLD='\033[1m'; RESET='\033[0m'
else
    RED=''; GREEN=''; YELLOW=''; BLUE=''; BOLD=''; RESET=''
fi

info()    { echo -e "${BLUE}[INFO]${RESET} $*"; }
ok()      { echo -e "  ${GREEN}[OK]${RESET}      $*"; }
installing() { echo -e "  ${YELLOW}[INSTALL]${RESET} $*"; }
fail()    { echo -e "  ${RED}[FAIL]${RESET}    $*"; }
pass()    { echo -e "  ${GREEN}[PASS]${RESET}    $*"; }
warn_msg(){ echo -e "  ${YELLOW}[WARN]${RESET}    $*"; }
skip()    { echo -e "  ${GREEN}[SKIP]${RESET}    $*"; }
run_msg() { echo -e "  ${BLUE}[RUN]${RESET}     $*"; }
dry_msg() { echo -e "  ${YELLOW}[DRY-RUN]${RESET} $*"; }

# ─── Argument Parsing ────────────────────────────────────────────────────────

MODE="prod"
NON_INTERACTIVE=false
CHECK_ONLY=false
DRY_RUN=false

usage() {
    cat <<'EOF'
Project Bootstrap (reads onboard.yml)

Usage: ./bootstrap.sh [OPTIONS]

Options:
  --mode dev|prod    dev = maintainer setup, prod = end-user deploy (default: prod)
  --non-interactive  Accept all defaults without prompting
  --check-only       Run validation checks only
  --dry-run          Show what would happen without executing destructive actions
  --help             Show this help

EOF
    exit 0
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --mode)       MODE="${2:-prod}"; shift 2 ;;
        --non-interactive) NON_INTERACTIVE=true; shift ;;
        --check-only) CHECK_ONLY=true; shift ;;
        --dry-run)    DRY_RUN=true; shift ;;
        --help|-h)    usage ;;
        *)            echo "Unknown option: $1"; usage ;;
    esac
done

# ─── Dependency Checks ──────────────────────────────────────────────────────

if ! command -v python3 &>/dev/null; then
    echo "ERROR: python3 is required but not found."
    echo "  RHEL/Fedora: sudo dnf install -y python3"
    echo "  Debian/Ubuntu: sudo apt-get install -y python3"
    echo "  macOS: brew install python3"
    exit 1
fi

if ! python3 -c "import yaml" 2>/dev/null; then
    echo "ERROR: PyYAML is required but not installed."
    echo "  RHEL/Fedora: sudo dnf install -y python3-pyyaml"
    echo "  Debian/Ubuntu: sudo apt-get install -y python3-yaml"
    echo "  pip: pip3 install pyyaml"
    echo "  macOS: pip3 install pyyaml"
    exit 1
fi

# ─── Manifest Discovery ─────────────────────────────────────────────────────

MANIFEST=""
for candidate in onboard.yml onboard.json agnosticd/onboard.yml \
                 agnosticd/onboard.json .onboard.yml .onboard.json; do
    if [[ -f "$candidate" ]]; then
        MANIFEST="$candidate"
        break
    fi
done

if [[ -z "$MANIFEST" ]]; then
    echo "ERROR: No onboard.yml found in this directory."
    echo "  Searched: onboard.yml, onboard.json, agnosticd/onboard.yml,"
    echo "           agnosticd/onboard.json, .onboard.yml, .onboard.json"
    exit 1
fi

# ─── YAML → JSON Conversion ─────────────────────────────────────────────────

MANIFEST_JSON=$(mktemp)
trap 'rm -f "$MANIFEST_JSON"' EXIT

python3 -c "
import yaml, json, sys
with open(sys.argv[1]) as f:
    data = yaml.safe_load(f)
json.dump(data, sys.stdout)
" "$MANIFEST" > "$MANIFEST_JSON"

# ─── JSON Query Helper ──────────────────────────────────────────────────────

# Usage: manifest_get '.field.path'  or  manifest_get '.array[0].name'
# Returns raw value (unquoted for scalars, JSON for objects/arrays).
manifest_get() {
    local query="$1"
    if command -v jq &>/dev/null; then
        jq -r "$query // empty" "$MANIFEST_JSON"
    else
        python3 -c "
import json, sys, functools, re

with open(sys.argv[2]) as f:
    data = json.load(f)

query = sys.argv[1]
result = data

for token in re.findall(r'\.(\w+)|\[(\d+)\]', query):
    key, idx = token
    if result is None:
        break
    if key:
        result = result.get(key) if isinstance(result, dict) else None
    elif idx:
        i = int(idx)
        result = result[i] if isinstance(result, list) and i < len(result) else None

if result is None or result == '':
    sys.exit(0)
if isinstance(result, (dict, list)):
    json.dump(result, sys.stdout)
elif isinstance(result, bool):
    print(str(result).lower())
else:
    print(result)
" "$query" "$MANIFEST_JSON"
    fi
}

# Returns the number of elements in a JSON array at the given path.
manifest_len() {
    local query="$1"
    if command -v jq &>/dev/null; then
        jq -r "($query // []) | length" "$MANIFEST_JSON"
    else
        python3 -c "
import json, sys, re

with open(sys.argv[2]) as f:
    data = json.load(f)

query = sys.argv[1]
result = data
for token in re.findall(r'\.(\w+)|\[(\d+)\]', query):
    key, idx = token
    if result is None:
        break
    if key:
        result = result.get(key) if isinstance(result, dict) else None
    elif idx:
        i = int(idx)
        result = result[i] if isinstance(result, list) and i < len(result) else None

if isinstance(result, list):
    print(len(result))
else:
    print(0)
" "$query" "$MANIFEST_JSON"
    fi
}

# ─── Platform Detection ─────────────────────────────────────────────────────

detect_distro() {
    if [[ "$(uname -s)" == "Darwin" ]]; then
        echo "macos"
        return
    fi
    if [[ -f /etc/os-release ]]; then
        local id version_id major
        id="$(. /etc/os-release && echo "${ID:-}")"
        version_id="$(. /etc/os-release && echo "${VERSION_ID:-}")"
        major="${version_id%%.*}"
        case "$id" in
            rhel|redhat|centos) echo "rhel${major}" ;;
            fedora)             echo "fedora" ;;
            debian|ubuntu)      echo "debian" ;;
            *)                  echo "unknown" ;;
        esac
    else
        echo "unknown"
    fi
}

# ─── Version Comparison ─────────────────────────────────────────────────────

# Returns 0 if $1 >= $2 (dot-separated numeric comparison)
version_gte() {
    local have="$1" need="$2"
    local IFS='.'
    local -a have_parts=($have) need_parts=($need)
    local i
    for (( i=0; i<${#need_parts[@]}; i++ )); do
        local h="${have_parts[$i]:-0}"
        local n="${need_parts[$i]:-0}"
        if (( h > n )); then return 0; fi
        if (( h < n )); then return 1; fi
    done
    return 0
}

# ─── Variable Store ─────────────────────────────────────────────────────────

# Associative array holding all collected config/prompt values.
declare -A VARS

# Substitute ${variable} references in a string with values from VARS.
# Unresolved references (no matching key) are replaced with empty string.
substitute_vars() {
    local text="$1"
    local key val
    for key in "${!VARS[@]}"; do
        val="${VARS[$key]}"
        text="${text//\$\{${key}\}/${val}}"
    done
    # Remove any remaining unresolved ${...} references
    text="$(echo "$text" | sed 's/\${[a-zA-Z_][a-zA-Z0-9_]*}//g')"
    echo "$text"
}

# ─── Prompt Helper ──────────────────────────────────────────────────────────

# prompt_for KEY "Prompt text" "default" ["choice1,choice2"] [required:true|false]
prompt_for() {
    local key="$1" prompt_text="$2" default="$3"
    local choices="${4:-}" required="${5:-false}"

    if [[ "$NON_INTERACTIVE" == "true" ]]; then
        VARS["$key"]="$default"
        return
    fi

    while true; do
        local display="  ${prompt_text}"
        [[ -n "$default" ]] && display+=" [${default}]"
        [[ -n "$choices" ]] && display+=" (${choices})"
        display+=": "

        read -rp "$display" value
        value="${value:-$default}"

        if [[ -n "$choices" && -n "$value" ]]; then
            local valid=false
            IFS=',' read -ra choice_arr <<< "$choices"
            for c in "${choice_arr[@]}"; do
                [[ "$value" == "$c" ]] && valid=true
            done
            if [[ "$valid" != "true" ]]; then
                echo "    Invalid choice. Options: $choices"
                continue
            fi
        fi

        if [[ "$required" == "true" && -z "$value" ]]; then
            echo "    This field is required."
            continue
        fi

        VARS["$key"]="$value"
        return
    done
}

# ─── Phase: Prerequisites ───────────────────────────────────────────────────

install_prerequisites() {
    local distro="$1" prereqs_path="$2" label="$3"
    local count
    count="$(manifest_len "$prereqs_path")"
    if (( count == 0 )); then return 0; fi

    echo ""
    echo -e "${BOLD}--- ${label} ---${RESET}"
    echo ""

    local i name check_cmd version_regex min_version install_cmd fallback_msg
    for (( i=0; i<count; i++ )); do
        name="$(manifest_get "${prereqs_path}[$i].name")"
        check_cmd="$(manifest_get "${prereqs_path}[$i].check_command")"
        version_regex="$(manifest_get "${prereqs_path}[$i].version_regex")"
        min_version="$(manifest_get "${prereqs_path}[$i].min_version")"

        install_cmd="$(manifest_get "${prereqs_path}[$i].install.${distro}")"
        if [[ -z "$install_cmd" ]]; then
            install_cmd="$(manifest_get "${prereqs_path}[$i].install.fallback")"
        fi

        local output=""
        if output=$(eval "$check_cmd" 2>&1); then
            if [[ -n "$version_regex" && -n "$min_version" ]]; then
                local version
                version=$(echo "$output" | python3 -c "
import re, sys
text = sys.stdin.read()
m = re.search(sys.argv[1], text)
print(m.group(1) if m else '0.0')
" "$version_regex" 2>/dev/null || echo "0.0")
                if version_gte "$version" "$min_version"; then
                    ok "${name} ${version} (>= ${min_version})"
                    continue
                else
                    installing "${name} ${version} is too old (need >= ${min_version})"
                fi
            else
                ok "${name} installed"
                continue
            fi
        else
            installing "${name} not found"
        fi

        if [[ -z "$install_cmd" ]]; then
            fail "No install command for ${name} on ${distro}."
            fallback_msg="$(manifest_get "${prereqs_path}[$i].install.fallback")"
            [[ -n "$fallback_msg" ]] && echo "      $fallback_msg"
            return 1
        fi

        if [[ "$DRY_RUN" == "true" ]]; then
            dry_msg "Would install ${name}: ${install_cmd}"
        else
            echo "            → Running: ${install_cmd}"
            if ! eval "$install_cmd"; then
                fail "Failed to install ${name}"
                return 1
            fi
            ok "${name} installed"
        fi
    done
}

# ─── Phase: Setup Steps ─────────────────────────────────────────────────────

run_setup_steps() {
    local count
    count="$(manifest_len ".setup_steps")"
    if (( count == 0 )); then return 0; fi

    echo ""
    echo -e "${BOLD}--- Setup Steps ---${RESET}"
    echo ""

    local i name check action prompt_var prompt_text default_val
    for (( i=0; i<count; i++ )); do
        name="$(manifest_get ".setup_steps[$i].name")"
        check="$(manifest_get ".setup_steps[$i].check")"
        action="$(manifest_get ".setup_steps[$i].action")"
        prompt_var="$(manifest_get ".setup_steps[$i].prompt_var")"
        prompt_text="$(manifest_get ".setup_steps[$i].prompt")"
        default_val="$(manifest_get ".setup_steps[$i].default")"

        if [[ -n "$prompt_var" ]]; then
            prompt_for "$prompt_var" "${prompt_text:-$prompt_var}" "${default_val:-}"
            local raw="${VARS[$prompt_var]}"
            VARS["$prompt_var"]="${raw/#\~/$HOME}"
        fi

        check="$(substitute_vars "$check")"
        action="$(substitute_vars "$action")"

        if eval "$check" &>/dev/null; then
            skip "${name} (already done)"
        elif [[ "$DRY_RUN" == "true" ]]; then
            dry_msg "Would run: ${action}"
        else
            run_msg "${name}"
            if ! ( eval "$action" ); then
                fail "${name}"
                return 1
            fi
        fi
    done
}

# ─── Load Saved Config (for --check-only) ────────────────────────────────────

# Loads previously saved config values and manifest defaults into VARS so that
# validation commands can resolve ${variable} references without prompting.
load_saved_config() {
    local output_file
    output_file="$(manifest_get ".config.output_file")"
    if [[ -n "$output_file" && -f "$output_file" ]]; then
        local line k v
        while IFS= read -r line; do
            [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
            k="${line%%:*}"
            v="${line#*: }"
            if [[ -z "${VARS[$k]+_}" ]]; then
                VARS["$k"]="$v"
            fi
        done < "$output_file"
        info "Loaded config from ${output_file}"
    fi

    local count i key default_val
    count="$(manifest_len ".config.prompts")"
    for (( i=0; i<count; i++ )); do
        key="$(manifest_get ".config.prompts[$i].key")"
        default_val="$(manifest_get ".config.prompts[$i].default")"
        if [[ -z "${VARS[$key]+_}" && -n "$default_val" ]]; then
            VARS["$key"]="${default_val/#\~/$HOME}"
        fi
    done
}

# ─── Phase: Configuration ───────────────────────────────────────────────────

configure() {
    local count
    count="$(manifest_len ".config.prompts")"
    if (( count == 0 )); then return 0; fi

    # Pre-load existing config values so re-runs use them as defaults
    local output_file
    output_file="$(manifest_get ".config.output_file")"
    if [[ -n "$output_file" && -f "$output_file" ]]; then
        local line k v
        while IFS= read -r line; do
            [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
            k="${line%%:*}"
            v="${line#*: }"
            if [[ -z "${VARS[$k]+_}" ]]; then
                VARS["$k"]="$v"
            fi
        done < "$output_file"
        info "Loaded previous config from ${output_file} (press Enter to keep values)"
    fi

    echo ""
    echo -e "${BOLD}--- Configuration ---${RESET}"
    echo ""

    local i key prompt_text default_val required choices choices_str
    for (( i=0; i<count; i++ )); do
        key="$(manifest_get ".config.prompts[$i].key")"
        prompt_text="$(manifest_get ".config.prompts[$i].prompt")"
        default_val="$(manifest_get ".config.prompts[$i].default")"
        required="$(manifest_get ".config.prompts[$i].required")"
        choices="$(manifest_get ".config.prompts[$i].choices")"

        # Use previously saved value as default if available
        if [[ -n "${VARS[$key]+_}" && -n "${VARS[$key]}" ]]; then
            default_val="${VARS[$key]}"
        fi

        choices_str=""
        if [[ -n "$choices" && "$choices" != "null" ]]; then
            choices_str="$(echo "$choices" | python3 -c "
import json, sys
arr = json.load(sys.stdin)
print(','.join(str(x) for x in arr)) if isinstance(arr, list) else print('')
" 2>/dev/null || echo "")"
        fi

        # Don't re-prompt if already set by a setup step prompt_var
        if [[ -z "${VARS[$key]+_}" ]]; then
            prompt_for "$key" "$prompt_text" "${default_val:-}" "$choices_str" "${required:-false}"
        else
            # Pre-loaded from config — still prompt but with saved value as default
            prompt_for "$key" "$prompt_text" "${default_val:-}" "$choices_str" "${required:-false}"
        fi
    done

    local output_file
    output_file="$(manifest_get ".config.output_file")"
    if [[ -n "$output_file" ]]; then
        mkdir -p "$(dirname "$output_file")"
        {
            echo "# Generated by bootstrap.sh — re-run to reconfigure"
            echo "# DO NOT commit this file (contains environment-specific values)"
            for (( i=0; i<count; i++ )); do
                key="$(manifest_get ".config.prompts[$i].key")"
                echo "${key}: ${VARS[$key]:-}"
            done
        } > "$output_file"
        info "Config saved to: ${output_file}"

        local gitignore
        gitignore="$(manifest_get ".config.gitignore")"
        if [[ "$gitignore" == "true" ]]; then
            if ! grep -qF "$output_file" .gitignore 2>/dev/null; then
                echo "$output_file" >> .gitignore
                info "Added ${output_file} to .gitignore"
            fi
        fi
    fi
}

# ─── Phase: Populate Secrets ──────────────────────────────────────────────────

populate_secrets() {
    local account="${VARS[account]:-}"
    local agd_root="${VARS[agnosticd_root]:-$HOME/agnosticd-v2}"
    local secrets_dir="${agd_root%/*}/agnosticd-v2-secrets"
    local secrets_file="${secrets_dir}/secrets-${account}.yml"

    echo ""
    echo -e "${BOLD}--- Secrets ---${RESET}"
    echo ""

    if [[ -z "$account" ]]; then
        fail "No account name set — cannot scaffold secrets file."
        return 1
    fi

    # Scaffold from template if missing
    if [[ ! -f "$secrets_file" ]]; then
        if [[ "$DRY_RUN" == "true" ]]; then
            dry_msg "Would create ${secrets_file} from template"
        else
            mkdir -p "$secrets_dir"
            cp deploy/vars/secrets.yml.example "$secrets_file"
            info "Created ${secrets_file} from template"
        fi
    else
        info "Secrets file exists: ${secrets_file}"
    fi

    # Read existing non-placeholder values as defaults
    local cur_key="" cur_secret="" cur_domain="" cur_pull=""
    if [[ -f "$secrets_file" ]]; then
        cur_key=$(yq -r '.aws_access_key_id // ""' "$secrets_file" 2>/dev/null || true)
        cur_secret=$(yq -r '.aws_secret_access_key // ""' "$secrets_file" 2>/dev/null || true)
        cur_domain=$(yq -r '.base_domain // ""' "$secrets_file" 2>/dev/null || true)
        cur_pull=$(yq -r '.ocp4_pull_secret // ""' "$secrets_file" 2>/dev/null || true)
    fi

    # Strip placeholder markers
    [[ "$cur_key" == *YOUR* || "$cur_key" == *"<"* ]] && cur_key=""
    [[ "$cur_secret" == *YOUR* || "$cur_secret" == *"<"* ]] && cur_secret=""
    [[ "$cur_domain" == *YOUR* || "$cur_domain" == *"<"* ]] && cur_domain=""
    [[ "$cur_pull" == *YOUR* || "$cur_pull" == *"<"* ]] && cur_pull=""

    # Auto-detect AWS credentials from ~/.aws/credentials if not already set
    if [[ -z "$cur_key" && -f "$HOME/.aws/credentials" ]]; then
        cur_key=$(awk -F= '/^aws_access_key_id/{gsub(/[ \t]/,"",$2); print $2; exit}' "$HOME/.aws/credentials")
        cur_secret=$(awk -F= '/^aws_secret_access_key/{gsub(/[ \t]/,"",$2); print $2; exit}' "$HOME/.aws/credentials")
        [[ -n "$cur_key" ]] && info "Auto-detected AWS credentials from ~/.aws/credentials"
    fi

    # Fall back to config values for base_domain
    [[ -z "$cur_domain" ]] && cur_domain="${VARS[base_domain]:-}"

    # Read pull secret from file if no value in secrets file yet
    local ps_path="${VARS[pull_secret_path]:-}"
    ps_path="${ps_path/#\~/$HOME}"
    if [[ -z "$cur_pull" && -n "$ps_path" && -f "$ps_path" ]]; then
        cur_pull="$(cat "$ps_path")"
        [[ -n "$cur_pull" ]] && info "Auto-loaded pull secret from ${ps_path}"
    fi

    # Prompt for each secret value
    prompt_for _aws_key    "AWS Access Key ID"     "$cur_key"    "" true
    prompt_for _aws_secret "AWS Secret Access Key" "$cur_secret" "" true
    prompt_for _base_domain "Base domain"          "$cur_domain" "" true

    # Pull secret is long; show a truncated default for readability
    local pull_display=""
    if [[ -n "$cur_pull" ]]; then
        pull_display="(${#cur_pull} chars loaded — press Enter to keep)"
    fi
    if [[ -n "$cur_pull" && "$NON_INTERACTIVE" != "true" ]]; then
        local pull_input
        read -rp "  OpenShift pull secret ${pull_display}: " pull_input
        VARS[_pull_secret]="${pull_input:-$cur_pull}"
    else
        VARS[_pull_secret]="${cur_pull}"
    fi

    # Write values into secrets file
    if [[ "$DRY_RUN" == "true" ]]; then
        dry_msg "Would write aws_access_key_id to ${secrets_file}"
        dry_msg "Would write aws_secret_access_key to ${secrets_file}"
        dry_msg "Would write base_domain=${VARS[_base_domain]} to ${secrets_file}"
        dry_msg "Would write ocp4_pull_secret (${#VARS[_pull_secret]} chars) to ${secrets_file}"
    else
        yq -i ".aws_access_key_id = \"${VARS[_aws_key]}\"" "$secrets_file"
        yq -i ".aws_secret_access_key = \"${VARS[_aws_secret]}\"" "$secrets_file"
        yq -i ".base_domain = \"${VARS[_base_domain]}\"" "$secrets_file"

        # Pull secret may contain special chars; use a temp file for safe injection
        local pull_tmp
        pull_tmp=$(mktemp)
        printf '%s' "${VARS[_pull_secret]}" > "$pull_tmp"
        yq -i ".ocp4_pull_secret = load_str(\"${pull_tmp}\")" "$secrets_file"
        rm -f "$pull_tmp"

        ok "Secrets written to ${secrets_file}"
    fi
}

# ─── Phase: Validation + Readiness Gate ──────────────────────────────────────

validate() {
    local count
    count="$(manifest_len ".validation")"

    echo ""
    echo -e "${BOLD}--- Validation ---${RESET}"
    echo ""

    local required_total=0 required_passed=0 warnings=0

    local i name command required_flag fail_message
    for (( i=0; i<count; i++ )); do
        name="$(manifest_get ".validation[$i].name")"
        command="$(manifest_get ".validation[$i].command")"
        required_flag="$(manifest_get ".validation[$i].required")"
        fail_message="$(manifest_get ".validation[$i].fail_message")"

        command="$(substitute_vars "$command")"
        fail_message="$(substitute_vars "$fail_message")"

        if [[ "$required_flag" == "true" ]]; then
            required_total=$((required_total + 1))
        fi

        if eval "$command" &>/dev/null; then
            pass "${name}"
            if [[ "$required_flag" == "true" ]]; then
                required_passed=$((required_passed + 1))
            fi
        else
            if [[ "$required_flag" == "true" ]]; then
                fail "${name}"
            else
                warn_msg "${name}"
                warnings=$((warnings + 1))
            fi
            [[ -n "$fail_message" ]] && echo "      ${fail_message}"
        fi
    done

    echo ""
    if (( required_total == 0 )); then
        info "No required checks defined. ${warnings} warning(s)."
        return 0
    fi

    if (( required_passed == required_total )); then
        info "Readiness: ${required_passed}/${required_total} required checks passed (${warnings} warning(s)). Ready to deploy!"
        return 0
    else
        local failed=$((required_total - required_passed))
        fail "Readiness: ${required_passed}/${required_total} required checks passed (${warnings} warning(s))"
        fail "BLOCKED: ${failed} required check(s) failed. Fix the issues above before deploying."
        return 1
    fi
}

# ─── Phase: Quota Checks ─────────────────────────────────────────────────────

run_quota_checks() {
    local count
    count="$(manifest_len ".quota_checks")"
    if (( count == 0 )); then return 0; fi

    echo ""
    echo -e "${BOLD}--- Quota Check ---${RESET}"
    echo ""

    local total=0 passed=0
    local i label needed limit_cmd usage_cmd fail_message
    for (( i=0; i<count; i++ )); do
        label="$(manifest_get ".quota_checks[$i].label")"
        needed="$(manifest_get ".quota_checks[$i].needed")"
        limit_cmd="$(manifest_get ".quota_checks[$i].limit_command")"
        usage_cmd="$(manifest_get ".quota_checks[$i].usage_command")"
        fail_message="$(manifest_get ".quota_checks[$i].fail_message")"

        limit_cmd="$(substitute_vars "$limit_cmd")"
        usage_cmd="$(substitute_vars "$usage_cmd")"
        fail_message="$(substitute_vars "$fail_message")"

        total=$((total + 1))

        local limit_val usage_val available
        limit_val=$(eval "$limit_cmd" 2>/dev/null | tr -d '[:space:]' || echo "0")
        usage_val=$(eval "$usage_cmd" 2>/dev/null | tr -d '[:space:]' || echo "0")

        # Truncate decimals for integer comparison
        limit_val="${limit_val%%.*}"
        usage_val="${usage_val%%.*}"
        limit_val="${limit_val:-0}"
        usage_val="${usage_val:-0}"

        available=$((limit_val - usage_val))

        if (( available >= needed )); then
            pass "${label}: need ${needed}, available ${available} (limit: ${limit_val}, used: ${usage_val})"
            passed=$((passed + 1))
        else
            fail "${label}: need ${needed}, available ${available} (limit: ${limit_val}, used: ${usage_val})"
            [[ -n "$fail_message" ]] && echo "      ${fail_message}"
        fi
    done

    echo ""
    if (( passed == total )); then
        info "Quota: ${passed}/${total} checks passed. Sufficient capacity."
        return 0
    else
        local failed=$((total - passed))
        fail "Quota: ${passed}/${total} checks passed"
        fail "BLOCKED: Insufficient quota. Fix the issues above before deploying."
        return 1
    fi
}

# ─── Phase: Post-Setup ──────────────────────────────────────────────────────

show_post_setup() {
    local message
    message="$(manifest_get ".post_setup.message")"
    if [[ -z "$message" ]]; then return; fi

    echo ""
    echo -e "${BOLD}--- Next Steps ---${RESET}"
    echo ""
    substitute_vars "$message"
}

# ─── Main ────────────────────────────────────────────────────────────────────

main() {
    local project_name project_desc
    project_name="$(manifest_get ".name")"
    project_desc="$(manifest_get ".description")"

    echo ""
    local mode_label="${MODE} mode"
    [[ "$DRY_RUN" == "true" ]] && mode_label+=" / dry-run"
    echo -e "${BOLD}=== ${project_name} Setup (${mode_label}) ===${RESET}"
    [[ -n "$project_desc" ]] && echo "$project_desc"
    echo ""

    local distro
    distro="$(detect_distro)"
    info "Detected platform: ${distro}"
    info "Manifest: ${MANIFEST}"

    if [[ "$CHECK_ONLY" == "true" ]]; then
        load_saved_config
        local rc=0
        validate || rc=1
        run_quota_checks || rc=1
        show_post_setup
        exit $rc
    fi

    # --- Prerequisites ---
    install_prerequisites "$distro" ".prerequisites" "Prerequisites"

    # Dev mode: extra prerequisites
    if [[ "$MODE" == "dev" ]]; then
        local dev_extras_count
        dev_extras_count="$(manifest_len ".modes.dev.extra_prerequisites")"
        if (( dev_extras_count > 0 )); then
            install_prerequisites "$distro" ".modes.dev.extra_prerequisites" "Dev Prerequisites"
        fi
    fi

    # --- Setup Steps ---
    run_setup_steps

    # --- Configuration ---
    configure

    # --- Secrets ---
    populate_secrets

    # --- Validation + Readiness Gate ---
    local validation_passed=true
    if ! validate; then
        validation_passed=false
    fi

    # --- Quota Checks ---
    local quota_passed=true
    if ! run_quota_checks; then
        quota_passed=false
    fi

    # --- Post-Setup ---
    show_post_setup

    # --- Prod Deploy (only if both gates passed) ---
    if [[ "$MODE" == "prod" && "$validation_passed" == "true" && "$quota_passed" == "true" ]]; then
        local deploy_cmd
        deploy_cmd="$(manifest_get ".modes.prod.post_validation_command")"
        if [[ -n "$deploy_cmd" ]]; then
            deploy_cmd="$(substitute_vars "$deploy_cmd")"
            echo ""
            echo -e "${BOLD}--- Deploying ---${RESET}"
            echo ""
            if [[ "$DRY_RUN" == "true" ]]; then
                dry_msg "Would run: ${deploy_cmd}"
            else
                info "Running: ${deploy_cmd}"
                eval "$deploy_cmd"
            fi
        fi
    elif [[ "$MODE" == "prod" && ("$validation_passed" == "false" || "$quota_passed" == "false") ]]; then
        echo ""
        fail "Deployment skipped — resolve all failures above first."
        exit 1
    fi
}

main
